### ISSUE TITLE
Crash if image doesn't exist

### ISSUE THREAD

**Issue by rondey** [PeterStaev/nativescript-image-swipe#41]
Example: loading the image "https://www.google.it/alakazam.jpg" will result in this error:
```
06-17 10:16:02.233  5303  5303 E AndroidRuntime:     com.tns.Runtime.callJSMethodNative(Native Method)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:987)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:967)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:959)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:        at com.tns.Runtime.callJSMethodNative(Native Method)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:987)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:967)
06-17 10:16:02.233  5303  5303 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onError failed
System.err: 
System.err: Error: java.lang.AbstractMethodError: abstract method "void org.nativescript.widgets.Async$CompleteCallback.onError(java.lang.Object)"
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onError(Async_CompleteCallback.java:23)
System.err:     org.nativescript.widgets.Async$Image$DownloadImageTask.onPostExecute(Async.java:197)
System.err:     org.nativescript.widgets.Async$Image$4$1.run(Async.java:154)
System.err:     android.os.Handler.handleCallback(Handler.java:789)
System.err:     android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6541)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: File: "<unknown>, line: 0, column: -1
System.err: 
System.err: StackTrace: 
System.err: 
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onError(Async_CompleteCallback.java:23)
System.err:     at org.nativescript.widgets.Async$Image$DownloadImageTask.onPostExecute(Async.java:197)
System.err:     at org.nativescript.widgets.Async$Image$4$1.run(Async.java:154)
System.err:     at android.os.Handler.handleCallback(Handler.java:789)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.AbstractMethodError: abstract method "void org.nativescript.widgets.Async$CompleteCallback.onError(java.lang.Object)"
System.err:     ... 16 more
```

**Comment by PeterStaev** [comment]
Hey @rondey , this is a known limitation of the current implementation.
